<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Dashboard</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body class="bg-light">
<main class="container py-5">
    <h1 class="h3 mb-2">Dashboard</h1>
    <p class="text-muted mb-4">Skeleton dashboard generated by MetaFramework auth publishables.</p>

    <div class="d-flex flex-wrap gap-2">
        <a href="{{ url('/') }}" class="btn btn-outline-secondary">Home</a>
        <form method="POST" action="{{ route('logout') }}" class="m-0">
            @csrf
            <button type="submit" class="btn btn-dark">Logout</button>
        </form>
    </div>
</main>
</body>
</html>
